// Code generated by a template
using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.SqlClient;

namespace EntityFramework6.DevData.AspNetCore
{
    public class EF6ModelConnectionScope
    {

    }
}
