// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace EntityFramework6.DevData.AspNetCore
{
    public partial class Product: IQPArticle
    {
        public Product()
        {
		    Regions = new HashSet<Region>();
		    Parameters = new HashSet<ProductParameter>();
		    MobileTariffs = new HashSet<MobileTariff>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual Int32? Type { get; set; }
        public virtual String PDF { get; set; }
        public virtual String Legal { get; set; }
        public virtual String Benefit { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Int32? MarketingSign_ID { get; set; }
        public virtual DateTime? StartDate { get; set; }
        public virtual DateTime? EndDate { get; set; }
        public virtual String ArchiveTitle { get; set; }
        public virtual String ArchiveNotes { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual MarketingProduct MarketingProduct { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? MarketingProduct_ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<Region> Regions { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<ProductParameter> Parameters { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 1192)/Product MobileTariffs
		/// </summary>
		public  ICollection<MobileTariff> MobileTariffs { get; set; }

	}
}

