// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Quantumart.QP8.EntityFramework6.DevData
{
    public partial class ProductParameter: IQPArticle
    {
        public ProductParameter()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual Int32? GroupMapped_ID { get; set; }
        public virtual Int32? BaseParameter_ID { get; set; }
        public virtual Int32? Zone_ID { get; set; }
        public virtual Int32? Direction_ID { get; set; }
        public virtual Int32? SortOrder { get; set; }
        public virtual Double? NumValue { get; set; }
        public virtual String Value { get; set; }
        public virtual Int32? Unit_ID { get; set; }
        public virtual String Legal { get; set; }
        public virtual String ShortTitle { get; set; }
        public virtual String ShortValue { get; set; }
        public virtual Int32? MatrixParameter_ID { get; set; }
        public virtual Int32? OldSiteId { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual Product Product { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Product_ID { get; set; }

	}
}
	
